name: Daily Crawl Coupang Deals

on:
  schedule:
    - cron: '0 */8 * * *'  # 하루 3번(8시간마다) 실행
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run crawler
        run: python crawler.py
        
      - name: Send to Telegram
        run: python telegram_sender.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        
      - name: Commit and push if data changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data || true
          git commit -m "자동 업데이트: 쿠팡 핫딜 데이터 ($(date +'%Y-%m-%d'))" || true
          git push || true
